application: spojtweet
version: 1
runtime: python
api_version: 1
builtins:
- deferred: on
- appstats: on

handlers:
- url: /(robots.txt)
  static_files: \1
  upload: robots.txt
- url: /(spojtweet_bird.jpg)
  static_files: \1
  upload: spojtweet_bird.jpg
- url: /(root.html)
  static_files: \1
  upload: root.html
- url: /(favicon.ico)
  static_files: \1
  upload: favicon.ico
- url: /(spojtweet.css)
  static_files: \1
  upload: spojtweet.css
- url: /settings/login
  static_files: login.html
  upload: login.html
- url: /crawl.*
  script: main.py
  login: admin
- url: /admin.*
  script: main.py
  login: admin
- url: /settings.*
  script: main.py
  secure: always
- url: /.*
  script: main.py

admin_console:
  pages:
  - name: SpojTweet Admin
    url: /admin
