application: spojtweet
version: 1
runtime: python
api_version: 1
builtins:
- deferred: on

handlers:
- url: /(login.html)
  static_files: \1
  upload: login.html
- url: /admin.*
  script: main.py
  login: admin
- url: /twitter.*
  script: main.py
  secure: always
- url: /.*
  script: main.py

admin_console:
  pages:
  - name: SpojTweet Admin
    url: /admin
