application: spojtweet
version: 1
runtime: python
api_version: 1
builtins:
- deferred: on
- appstats: on

handlers:
- url: /(favicon.ico)
  static_files: \1
  upload: favicon.ico
- url: /settings/login
  static_files: login.html
  upload: login.html
- url: /admin.*
  script: main.py
  login: admin
- url: /settings.*
  script: main.py
  secure: always
- url: /.*
  script: main.py

admin_console:
  pages:
  - name: SpojTweet Admin
    url: /admin
