# coding=utf-8
#
# This list is based on [1], so it should be used and distributed under the
# terms of the Creative Commons Attribution-ShareAlike License.
# [1] http://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_of_place_names
#

"""Country name to demonym table."""

__author__ = "leandro@tia.mat.br (Leandro Pereira)"

COUNTRY_DEMONYMS = {
    'ERITREA': 'Eritrean',
    'PORTUGAL': 'Portuguese',
    'KOSOVO': 'Kosovan',
    'INDIA': 'Indian',
    'MONTENEGRO': 'Montenegrin',
    'NEW CALEDONIA': 'New Caledonian',
    'UZBEKISTAN': 'Uzbek',
    'TOGO': 'Togolese',
    'ARUBA': 'Aruban',
    'MICRONESIA': 'Micronesian',
    'IRAN': 'Irani',
    'MALTA': 'Maltese',
    'KIRIBATI': 'Kiribatian',
    'BARBADOS': 'Barbadian',
    'BENIN': 'Beninese',
    'IRAQ': 'Iraqi',
    'CHAD': 'Chadian',
    'SAINT HELENA': 'Saint Helenian',
    'TAJIKISTAN': 'Tajikistani',
    'COSTA RICA': 'Costa Rican',
    'ETHIOPIA': 'Ethiopian',
    'SWEDEN': 'Swede',
    'RWANDA': 'Rwandan',
    'OMAN': 'Omani',
    'SURINAME': 'Surinamer',
    'ZAMBIA': 'Zambian',
    'ANGUILLA': 'Anguillan',
    'NORWAY': 'Norwegian',
    'QATAR': 'Qatari',
    'PALAU': 'Palauan',
    'SUDAN': 'Sudanese',
    'DENMARK': 'Dane',
    'NEPAL': 'Nepalese',
    'AZERBAIJAN': 'Azerbaijani',
    'PAPUA NEW GUINEA': 'Guinean',
    'ZIMBABWE': 'Zimbabwean',
    'GABON': 'Gabonese',
    'GIBRALTAR': 'Gibraltarian',
    'SWAZILAND': 'Swazi',
    'VANUATU': 'Vanuatuan',
    'YEMEN': 'Yemeni',
    'VENEZUELA': 'Venezuelan',
    'ECUADOR': 'Ecuadorean',
    'BAHAMAS': 'Bahamian',
    'AUSTRALIA': 'Australian',
    'ENGLAND': 'Englishman',
    'KUWAIT': 'Kuwaiti',
    'TANZANIA': 'Tanzanian',
    'SCOTLAND': 'Scot',
    'CENTRAL AFRICAN REPUBLIC': 'Central African',
    'FRANCE': 'Frenchman',
    'TRINIDAD AND TOBAGO': 'Trinidadian and Tobagan',
    'ARMENIA': 'Armenian',
    'AUSTRIA': 'Austrian',
    'SRI LANKA': 'Sri Lankan',
    'CROATIA': 'Croat',
    'TURKS AND CAICOS ISLANDS': 'Turks and Caicos Islander',
    'COMOROS': 'Comoran',
    'TONGA': 'Tongan',
    'GEORGIA': 'Georgian',
    'HONDURAS': 'Honduran',
    'GUINEA-BISSAU': 'Guinean',
    'LIBYA': 'Libyan',
    'NORTHERN MARIANAS': 'Northern Mariana Islander',
    'MAYOTTE': 'Mahorais',
    'INDONESIA': 'Indonesian',
    'ANTARCTICA': 'Antarctican',
    'VIETNAM': 'Vietnamese',
    'MOZAMBIQUE': 'Mozambican',
    'SOUTH SUDAN': 'South Sudanese',
    'COLOMBIA': 'Colombian',
    'MARTINIQUE': 'Martinican',
    'SWITZERLAND': 'Swiss',
    'CANADA': 'Canadian',
    'MAURITANIA': 'Mauritanian',
    'LITHUANIA': 'Lithuanian',
    'CAMBODIA': 'Cambodian',
    'EGYPT': 'Egyptian',
    'CUBA': 'Cuban',
    'LEBANON': 'Lebanese',
    'SAINT PIERRE AND MIQUELON': 'Saint-Pierrais',
    'BOTSWANA': 'Botswanan',
    'SENEGAL': 'Senegalese',
    'CONGO': 'Congolese',
    'ALGERIA': 'Algerian',
    'MALI': 'Malian',
    'NEW ZEALAND': 'New Zealander',
    'VATICAN CITY': 'Vatican',
    'COOK ISLANDS': 'Cook Islander',
    'PAKISTAN': 'Pakistani',
    'REUNIONESE': 'Reunionese',
    'ANGOLA': 'Angolan',
    'PRINCIPEAN': 'Principean',
    'SAINT LUCIA': 'Saint Lucian',
    'GUYANA': 'Guyanese',
    'SAINT KITTS AND NEVIS': 'Kittsian',
    'MALAYSIA': 'Malaysian',
    'SAINT VINCENT AND THE GRENADINES': 'Saint Vincentian',
    'GHANA': 'Ghanaian',
    'IRELAND': 'Irishman',
    'SYRIA': 'Syrian',
    'NIGERIA': 'Nigerian',
    'NORTH KOREA': 'North Korean',
    'KYRGYZSTAN': 'Kirgizia',
    'BANGLADESH': 'Bangladeshi',
    'ESTONIA': 'Estonian',
    'SLOVENIA': 'Slovenian',
    'ICELAND': 'Icelander',
    'SEYCHELLES': 'Seychellois',
    'RUSSIA': 'Russian',
    'LESOTHO': 'Mosotho',
    'TUNISIA': 'Tunisian',
    'BRITISH VIRGIN ISLANDS': 'British Virgin Islander',
    'BOSNIA AND HERZEGOVINA': 'Bosnian',
    'MONACO': 'Monacan',
    'WALLIS AND FUTUNA': 'Wallis and Futuna Islander',
    'UKRAINE': 'Ukrainian',
    'BRUNEI': 'Bruneian',
    'ISRAEL': 'Israeli',
    'IVORY COAST': 'Ivoirian',
    'KHALISTAN': 'Sikhistan',
    'MEXICO': 'Mexican',
    'TUVALU': 'Tuvaluan',
    'SERBIA': 'Serbian',
    'CAPE VERDE': 'Cape Verdean',
    'UNITED KINGDOM': 'Briton',
    'MOROCCO': 'Moroccan',
    'NETHERLANDS': 'Holland',
    'UGANDA': 'Ugandan',
    'GRENADA': 'Grenadian',
    'THAILAND': 'Thai',
    'MONTSERRAT': 'Montserratian',
    'BOLIVIA': 'Bolivian',
    'SIERRA LEONE': 'Sierra Leonian',
    'BRAZIL': 'Brazilian',
    'MADAGASCAR': 'Madagascan',
    'ALBANIA': 'Albanian',
    'CZECH REPUBLIC': 'Czech',
    'SOUTH AFRICA': 'South African',
    'BRITAIN': 'Northern Ireland',
    'SINGAPORE': 'Singaporean',
    'GERMANY': 'German',
    'PUERTO RICO': 'Puerto Rican',
    'NIGER': 'Nigerien',
    'NICARAGUA': 'Nicaraguan',
    'MALAWI': 'Malawian',
    'NIUE': 'Niuean',
    'EAST TIMOR': 'East Timorese',
    'SAUDI ARABIA': 'Saudi',
    'ITALY': 'Italian',
    'PERU': 'Peruvian',
    'PHILIPPINES': 'Filipino',
    'KENYA': 'Kenyan',
    'BERMUDA': 'Bermudian',
    'FRENCH GUIANA': 'Guianese',
    'SOMALIA': 'Somali',
    'PALESTINE': 'Palestinian',
    'ARGENTINA': 'Argentinian',
    'CYPRUS': 'Cypriot',
    'BAHRAIN': 'Bahraini',
    'FALKLAND ISLANDS': 'Falkland Islander',
    'MALDIVES': 'Maldivian',
    'WESTERN SAHARA': 'Sahrawi',
    'CAYMAN ISLANDS': 'Caymanian',
    'MARSHALL ISLANDS': 'Marshallese',
    'MONGOLIA': 'Mongolian',
    'LATVIA': 'Latvian',
    'SLOVAKIA': 'Slovak',
    'LAOS': 'Lao',
    'BELGIUM': 'Belgian',
    'GAMBIA': 'Gambian',
    'BURKINA FASO': 'Burkinabe',
    'US VIRGIN ISLANDS': 'US Virgin Islander',
    'LIBERIA': 'Liberian',
    'AFGHANISTAN': 'Afghan',
    'KAZAKHSTAN': 'Kazakh',
    'GUAM': 'Guamanian',
    'AMERICAN SAMOA': 'American Samoan',
    'MOLDOVA': 'Moldavia',
    'MAURITIUS': 'Mauritian',
    'LIECHTENSTEIN': 'Liechtensteiner',
    'MYANMAR': 'Burma',
    'NAMIBIA': 'Namibian',
    'GREECE': 'Hellas',
    'WALES': 'Welshman',
    'NAURU': 'Nauruan',
    'BELIZE': 'Belizean',
    'FIJI': 'Fijian',
    'TAIWAN': 'Republic of China',
    'ROMANIA': 'Romanian',
    'GREENLAND': 'Greenlander',
    'TIBET': 'Tibetan',
    'EL SALVADOR': 'Salvadoran',
    'POLAND': 'Pole',
    'UNITED STATES OF AMERICA': 'American',
    'BRITTANY': 'Breton',
    'LUXEMBOURG': 'Luxembourger',
    'NORFOLK ISLAND': 'Norfolk Islander',
    'ANTIGUA AND BARBUDA': 'Antiguan',
    'CHRISTMAS ISLAND': 'Christmas Islander',
    'HUNGARY': 'Hungarian',
    'FAEROE ISLANDS': 'Faeroese',
    'EUROPEAN UNION': 'European',
    'SPAIN': 'Spaniard',
    'CATALONIA': 'Catalan',
    'JAMAICA': 'Jamaican',
    'SOLOMON ISLANDS': 'Solomon Islander',
    'UNITED ARAB EMIRATES': 'Emirati',
    'FINLAND': 'Finn',
    'COCOS ISLANDER': 'Cocos',
    'PITCAIRN ISLANDS': 'Pitcairner',
    'ANDORRA': 'Andorran',
    'DJIBOUTI': 'Djiboutian',
    'BELARUS': 'Byelorussia',
    'JORDAN': 'Jordanian',
    'MACEDONIA': 'Macedonian',
    'JAPAN': 'Japanese',
    'PARAGUAY': 'Paraguayan',
    'DOMINICAN REPUBLIC': 'Dominican',
    'HAITI': 'Haitian',
    'DOMINICA': 'Dominican',
    'TURKEY': 'Turk',
    'SAMOA': 'Samoan',
    'TURKMENISTAN': 'Turkmenia',
    'BHUTAN': 'Bhutanese',
    'URUGUAY': 'Uruguayan',
    'GUINEA': 'Guinean',
    'PANAMA': 'Panamanian',
    'EQUATORIAL GUINEA': 'Equatorial Guinean',
    'SAN MARINO': 'Sammarinese',
    'FRENCH POLYNESIA': 'Polynesian',
    'TOKELAU': 'Tokelauan',
    'GUATEMALA': 'Guatemalan',
    'CHILE': 'Chilean',
    'BURUNDI': 'Burundian',
    'CHINA': 'Chinese',
    'SOUTH KOREA': 'South Korean',
    'GUADELOUPE': 'Guadeloupean',
    'CAMEROON': 'Cameroonian',
    'BULGARIA': 'Bulgarian',
    'BOUVET ISLAND': 'Bouvetan',
    'BRITISH INDIAN OCEAN TERRITORY': 'British Indian',
    'BRUNEI DARUSSALAM': 'Bruneian',
    'COCOS (KEELING) ISLANDS': 'Cocos Islander',
    'CONGO, THE DEMOCRATIC REPUBLIC OF THE': 'Congolese',
    'CÔTE D\'IVOIRE': 'Ivorian',
    'FALKLAND ISLANDS (MALVINAS)': 'Falkland Islander',
    'FAROE ISLANDS': 'Faroese',
    'HEARD ISLAND AND MCDONALD ISLANDS': 'Heard Islander',
    'HOLY SEE (VATICAN CITY STATE)': 'Vatican Resident',
    'HONG KONG': 'Hongkongese',
    'IRAN, ISLAMIC REPUBLIC OF': 'Iranian',
    'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF': 'North Korean',
    'KOREA, REPUBLIC OF': 'Korean',
    'LAO PEOPLE\'S DEMOCRATIC REPUBLIC': 'Laotian',
    'LIBYAN ARAB JAMAHIRIYA': 'Libyan',
    'MACAO': 'Macanese',
    'MICRONESIA, FEDERATED STATES OF': 'Micronesian',
    'MOLDOVA, REPUBLIC OF': 'Moldovan',
    'NORTHERN MARIANA ISLANDS': 'Northern Marianan',
    'PALESTINIAN TERRITORY, OCCUPIED': 'Palestinian',
    'PITCAIRN': 'Pitcairn Islander',
    'RUSSIAN FEDERATION': 'Russian',
    'RÉUNION': 'Réunionese',
    'SAO TOME AND PRINCIPE': 'São Toméan',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'South Sandwich Islander',
    'SVALBARD AND JAN MAYEN': 'Svalbardian',
    'SYRIAN ARAB REPUBLIC': 'Syrian',
    'TAIWAN, PROVINCE OF CHINA': 'Taiwanese',
    'TANZANIA, UNITED REPUBLIC OF': 'Tanzanian',
    'TIMOR-LESTE': 'Timorese',
    'UNITED STATES': 'American',
    'UNITED STATES MINOR OUTLYING ISLANDS': 'American',
    'VIET NAM': 'Vietnamese',
    'VIRGIN ISLANDS, BRITISH': 'Virgin Islander',
    'VIRGIN ISLANDS, U.S.': 'Virgin Islander',
    '[CITIZEN OF THE WORLD]': 'Earthling',
    '[UNLISTED COUNTRY]': 'Unknownian',

}
